### ISSUE TITLE
ROpenSci Review - Georeferencing 

### ISSUE THREAD

**Issue by aurielfournier** [embruna/refsplitr#64]
authors_georef(), for example, uses ggmap::geocode to retrieve geo-coding information. Since a couple of weeks, however, keyless access to Google Maps Platform has been deprecated. Information about how to pass API keys to the function to make geocode work would be very helpful.

    excuting authors_georef() resulted in lots of error messages, with a loop at the end and a message that a number of geocoding queries are remaining
    -> if this is expected behaviour, would be good to address in documentation

**Comment by birderboone** [comment]
took out google api and added in a 4 stage looping procedure that seems to work well with dsk
