### ISSUE TITLE
plot_addresses_points error

### ISSUE THREAD

**Issue by embruna** [embruna/refsplitr#66]
When testing the vignette I found this error: 

```plot_addresses_points <- plot_addresses_points(example_georef$addresses)```

The points are all clustered in Africa, when they should be in N America, Australia, etc. 

Latitude and Longitude are reversed on the axis legends (and maybe that's the underlying problem?)

**Comment by aurielfournier** [comment]
fixed it

R thought the lats and longs were factors, and thus was not plotting them correctly. Silly R.
